spring:
  cloud:
    gcp:
      project-id: accessorflow
  datasource:
    url: jdbc:postgresql://localhost:5432/email_db
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true

logging:
  level:
    sg.edu.nus.iss.email: DEBUG
